import type { CapabilitiesContract } from "../capabilities.ts";

export const EXPECTED_CAPABILITIES = {
  version: "1",
  globalOptions: [
    { long: "--help", short: "-h", description: "Show help." },
    { long: "--json", description: "Emit the versioned JSON envelope." },
    { long: "--version", short: "-V", description: "Show the Maya version." },
  ],
  commands: [
    {
      name: "maya ask",
      category: "legacy-agent",
      summary: "Run one command through Maya's in-process agent loop.",
      description: "Run one terminal command through Maya's legacy in-process agent loop.",
      args: [{ name: "command", required: true, variadic: true }],
      options: [{
        long: "--provider",
        short: "-p",
        type: "string",
        description: "Brain provider: anthropic | gemini | ollama",
      }],
      supportsJson: true,
    },
    {
      name: "maya capabilities",
      category: "discovery",
      summary: "Return the full Maya CLI command contract.",
      description: "List every registered CLI command, argument, and option.",
      args: [],
      options: [],
      supportsJson: true,
    },
    {
      name: "maya live",
      category: "legacy-agent",
      summary: "Run one command with the live overlay bridge.",
      description: "Run one legacy agent command with the live overlay wired in.",
      args: [{ name: "command", required: true, variadic: true }],
      options: [{
        long: "--provider",
        short: "-p",
        type: "string",
        description: "Brain provider: anthropic | gemini | ollama",
      }],
      supportsJson: true,
    },
    {
      name: "maya mcp",
      category: "mcp",
      summary: "Start the MCP stdio server.",
      description: "Start Maya as an MCP stdio server.",
      args: [],
      options: [],
      supportsJson: true,
    },
    {
      name: "maya ping",
      category: "diagnostic",
      summary: "Verify the Anthropic key with a cheap API call.",
      description: "Run the small Anthropic connectivity check.",
      args: [],
      options: [],
      supportsJson: true,
    },
    {
      name: "maya setup",
      category: "mcp",
      summary: "Register Maya with supported coding-agent MCP clients.",
      description: "Register Maya with Claude Code and/or Codex MCP client config.",
      args: [{ name: "client", required: false, variadic: false }],
      options: [],
      supportsJson: true,
    },
    {
      name: "maya start",
      category: "runtime",
      summary: "Start the Maya daemon.",
      description: "Start the Maya daemon and optionally skip the overlay.",
      args: [],
      options: [{
        long: "--no-overlay",
        type: "boolean",
        description: "Run the daemon without launching the overlay.",
        defaultValue: true,
        negates: "overlay",
      }],
      supportsJson: true,
    },
    {
      name: "maya status",
      category: "runtime",
      summary: "Show daemon status.",
      description: "Report the Maya daemon status.",
      args: [],
      options: [],
      supportsJson: true,
    },
    {
      name: "maya stop",
      category: "runtime",
      summary: "Stop the Maya daemon.",
      description: "Stop the Maya daemon if it is running.",
      args: [],
      options: [],
      supportsJson: true,
    },
  ],
} satisfies CapabilitiesContract;
